name: Deploy Fly 1

on: 
  workflow_dispatch

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  APP_NAME: ${{ secrets.APP_NAME_1 }}
  REGION: ${{ secrets.REGION_1 }}
  
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: |
          sh ./fly-deploy.sh